version: "3.8"

services:
  backend:
    build: ./agro-backend
    ports:
      - "8000:8000"
    volumes:
      - ./agro-backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=agro
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  frontend:
    build: ./agro-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: agro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
